import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from "axios";
import {useQuery} from "react-query";
import {useEffect, useState} from "react";

const Home: NextPage = () => {
  const [value, setValue] = useState<string>("")

  const usePosts = () => {
    return useQuery("posts", async () => {
      const {data} = await axios.get("http://localhost:3000/todos")
      return data
    })
  }

  const {data, error, isFetching} = usePosts()

  const createPost = () => {
    
  }

  useEffect(() => {
    if (data) console.log(data)
  }, [data])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <button>Get posts</button>
        <input type="text" value={value} onChange={e => setValue(e.target.value)}/>
        <button onClick={createPost}>Create Post</button>
      </main>
    </div>
  )
}

export default Home
