import type {NextPage} from 'next'
import Head from 'next/head'
import styles from './Home.module.scss'
import {useState} from "react";
import {useTodos} from "../hooks/useTodos";
import {useMutation} from "react-query";
import {ITodo, PostsService} from "../app/services/posts.service";
import {Slide, toast, ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import {useRouter} from "next/router";
import Image from "next/image";
import profile from './../assets/icons/profile-circle.svg'

const Home: NextPage = () => {
  const [value, setValue] = useState<string>("")
  const [list, setList] = useState<ITodo[]>([])

  const {isLoading, todos, refetch} = useTodos()

  const {isLoading: createLoading, mutateAsync} = useMutation('create country', (title: string) => {
      return PostsService.createTodo(title)
    },
    {
      onSuccess: () => {
        refetch()
        notify()
        setValue("")
      },
      onError: () => {
        toast.error('🦄 Error', {
          position: "top-right",
          autoClose: 5000,
          hideProgressBar: false,
          closeOnClick: true,
          pauseOnHover: true,
          draggable: true,
          progress: undefined,
        });
      }
    }
  )

  const handleCreateTodo = async () => {
    await mutateAsync(value)
  }

  const notify = () => toast.success(`Successfully created todo: ${value}`, {
    position: "top-right",
    autoClose: 5000,
    hideProgressBar: false,
    closeOnClick: true,
    pauseOnHover: true,
    draggable: true,
    progress: undefined,
    transition: Slide
  });

  const {push} = useRouter()

  const handleNavigate = (id: number) => {
    push(`/country/${id}`)
  }

  return (
    <main>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <header>
        <div className={styles.container}>
          <div className={styles.headerProfile}>
            <Image src={profile} alt="profile"/>
          </div>
        </div>
      </header>
      <section className={styles.todoSection}>
        <div className={styles.container}>
          <div className={styles.todoWrapper}>
            <h1>Your Tasks</h1>
            <div className={styles.todoList}>
              {todos?.map(todo => (
                <div key={todo?.id}
                     onClick={() => handleNavigate(todo?.id)}
                     className={styles.todoItem}>
                  <a>{todo.title}</a>
                  <div className={styles.todoItemButtons}>
                  </div>
                </div>
              ))}
            </div>
            <div className={styles.todoWrapperFooter}>
              <input type="text" value={value} onChange={e => setValue(e.target.value)}/>
              <button onClick={handleCreateTodo}>Add</button>
            </div>
          </div>

        </div>
        <div className={`${styles.blurCircle} ${styles.circleRight}`}></div>
        <div className={`${styles.blurCircle} ${styles.circleLeft}`}></div>
        <div className={styles.circle}></div>
      </section>
      <div className={`${styles.loader} ${isLoading || createLoading ? styles.loaderActive : ""}`}>Loading...</div>

      <ToastContainer/>
    </main>
  )
}

export default Home
